/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sss;
import java.sql.DriverManager;
import java.sql.Connection ; 
import java.sql.SQLException ; 
import java.sql.Statement ;
import java.sql.ResultSet ;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ehab Khaled
 */
public class Empolyee extends javax.swing.JFrame {
public int ID_num ; 
 public static int [] ID_col = new int [10];
    /**
     * Creates new form Empolyee
     */
    public Empolyee() {
        initComponents();
                 int i =0 ;
                      try{
    
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Security System", "Hatem", "133147");
    Statement stmt =  con.createStatement() ; 
    String SQL = "SELECT * FROM employees" ; 
    ResultSet rs = stmt.executeQuery(SQL);
     
    while(rs.next()){
  ID_col[i] = rs.getInt("ID");
    i++ ;
    }
    }
        catch (SQLException err){
            System.out.println(err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        id = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        check = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ID Validation");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 80, 40, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome in your company");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 20, 260, 40);

        login.setFont(new java.awt.Font("Segoe Script", 3, 11)); // NOI18N
        login.setText("Confirm");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(260, 190, 90, 30);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(160, 130, 110, 30);

        back.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(80, 190, 80, 30);
        jPanel1.add(check);
        check.setBounds(80, 170, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hatem Moahmed\\Desktop\\microsoft-sign-at-the-entrance-of-their-silicon-valley-campus-471179856-5c3d5d9a46e0fb00016dd455.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 410, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed
int counter=0,flag =0,ID=123;
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       ID_num =Integer.parseInt(id.getText());
       int x , chk =0 ;
       
        for(x=0 ; x<10 ; x++){
           
            if (ID_num == ID_col[x]){
                  
                JOptionPane.showMessageDialog(null, "ID Found ,Welcome Sir", "Entrance Successful" ,1);
                chk ++ ;
                break ;
            }  
        }
   if (chk==0){
      if(flag<2)
      {
          JOptionPane.showMessageDialog(this, "ID is not valid", "Warning", JOptionPane.ERROR_MESSAGE);
      }
       
      /* try {
           TimeUnit.SECONDS.sleep(1);
       } catch (InterruptedException ex) {
           Logger.getLogger(Empolyee.class.getName()).log(Level.SEVERE, null, ex);
       }*/
       flag++;
       id.setText("");
   }
  
       
   if(flag==3 &&counter<2)
    {
        counter++;
        
       
        
        try {
           TimeUnit.SECONDS.sleep(1);
       } catch (InterruptedException ex) {
           Logger.getLogger(Empolyee.class.getName()).log(Level.SEVERE, null, ex);
       }
         
        flag=0;
    }
   if(flag==0 && counter<2&& chk ==0)
   {
       JOptionPane.showMessageDialog(this, "you enterd a wrong ID pleas check your ID and login", "warning", JOptionPane.WARNING_MESSAGE);
        /*login.setEnabled(false);
        id.setEnabled(false);
        password.setEnabled(false);
        check.setText("");*/
   }
   
   if(counter==2)
   {
       counter=0;
       
       JOptionPane.showMessageDialog(this, "alarm", "alarm set", JOptionPane.ERROR_MESSAGE);
   }  
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
 this.setVisible(false);
        new Welcome().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empolyee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel check;
    private javax.swing.JPasswordField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
