/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Security_System;

/**
 *
 * @author Ehab Khaled
 */
public class Customer_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cusomer
     */
    public Customer_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Finish_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Entarnce_Num = new javax.swing.JTextField();
        Get_Entrance_No = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Status ");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setText("Welcome in our company");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 340, 41);

        Finish_button.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        Finish_button.setText("Finish");
        Finish_button.setEnabled(false);
        Finish_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finish_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Finish_button);
        Finish_button.setBounds(331, 160, 100, 33);

        jLabel2.setFont(new java.awt.Font("MS Mincho", 1, 18)); // NOI18N
        jLabel2.setText("Your number is : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 170, 19);

        Entarnce_Num.setEditable(false);
        Entarnce_Num.setEnabled(false);
        Entarnce_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entarnce_NumActionPerformed(evt);
            }
        });
        jPanel1.add(Entarnce_Num);
        Entarnce_Num.setBounds(220, 120, 97, 20);

        Get_Entrance_No.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        Get_Entrance_No.setText("Get entrance number");
        Get_Entrance_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get_Entrance_NoActionPerformed(evt);
            }
        });
        jPanel1.add(Get_Entrance_No);
        Get_Entrance_No.setBounds(22, 63, 191, 33);

        Back_button.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        Back_button.setText("Back");
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_button);
        Back_button.setBounds(30, 160, 90, 33);

        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entarnce_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entarnce_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entarnce_NumActionPerformed

    private void Finish_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finish_buttonActionPerformed
        Entarnce_Num.setText("");
        Entarnce_Num.setEnabled(false);
        Finish_button.setEnabled(false);
        //System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_Finish_buttonActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
this.setVisible(false);
        new Welcome_GUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_buttonActionPerformed
    int counter =0;
    private void Get_Entrance_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get_Entrance_NoActionPerformed
        Entarnce_Num.setEnabled(true);
        Entarnce_Num.setText(""+(200+counter));
        counter++;
        Finish_button.setEnabled(true);
    }//GEN-LAST:event_Get_Entrance_NoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JTextField Entarnce_Num;
    private javax.swing.JButton Finish_button;
    private javax.swing.JButton Get_Entrance_No;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
