/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Security_System;

import java.sql.DriverManager;
import java.sql.Connection ; 
import java.sql.SQLException ; 
import java.sql.Statement ;
import java.sql.ResultSet ;
/**
 *
 * @author Ehab Khaled
 */
public class Welcome_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Empolyee_Button = new javax.swing.JRadioButton();
        Customer_button = new javax.swing.JRadioButton();
        Confirm_button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome Window ");

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(125, 11, 159, 47);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login As : ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 68, 110, 30);

        Empolyee_Button.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Empolyee_Button.setForeground(new java.awt.Color(255, 255, 255));
        Empolyee_Button.setText("Employee");
        Empolyee_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empolyee_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(Empolyee_Button);
        Empolyee_Button.setBounds(153, 69, 87, 27);

        Customer_button.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Customer_button.setForeground(new java.awt.Color(255, 255, 255));
        Customer_button.setText("Customer");
        Customer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Customer_button);
        Customer_button.setBounds(153, 114, 87, 27);

        Confirm_button.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Confirm_button.setText("Confirm");
        Confirm_button.setEnabled(false);
        Confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Confirm_button);
        Confirm_button.setBounds(300, 150, 87, 29);

        Cancel_button.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Cancel_button.setText("Cancel");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel_button);
        Cancel_button.setBounds(50, 150, 90, 30);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_buttonActionPerformed
        Confirm_button.setEnabled(true);
        Empolyee_Button.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_buttonActionPerformed

    private void Empolyee_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empolyee_ButtonActionPerformed
        
        Confirm_button.setEnabled(true);
        Customer_button.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Empolyee_ButtonActionPerformed

    private void Confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_buttonActionPerformed
  if(Empolyee_Button.isSelected())
       {     Empolyee_GUI f1 = new Empolyee_GUI();
             Welcome_GUI f2 = new Welcome_GUI();
            
             f2.setVisible(false);
             f1.setVisible(true);
             
       }
       else if(Customer_button.isSelected())
       {
             this.setVisible(false);
             new Customer_GUI().setVisible(true);
       }              // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_buttonActionPerformed

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                         try{
    
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Security System", "Hatem", "133147");
    Statement stmt =  con.createStatement() ; 
                         }
                        catch (SQLException err){
            System.out.println(err.getMessage());
        }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_button;
    private javax.swing.JButton Confirm_button;
    private javax.swing.JRadioButton Customer_button;
    private javax.swing.JRadioButton Empolyee_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
